name: Build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: pwsh
        run: |
          choco install ninja -y
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          "VCPKG_ROOT=C:\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Bootstrap ZeroTier dependencies
        shell: bash
        run: |
          bash scripts/bootstrap-deps.sh

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        run: |
          cmake --build build --parallel

      - name: Find executables
        shell: pwsh
        run: |
          Get-ChildItem -Path build -Recurse -Filter *.exe |
            Select-Object FullName

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: PC-GRID0-Windows
          path: |
            build/**/*.exe
